# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lidar_Scanner_Realtime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftOSC', '~> 1.3'
  # Pods for Lidar_Scanner_Realtime

  target 'Lidar_Scanner_RealtimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lidar_Scanner_RealtimeUITests' do
    # Pods for testing
  end

end
